### ISSUE TITLE
GetObject with streaming, hangs

### ISSUE THREAD

**Issue by kosmasgiannis** [chilts/awssum-amazon-s3#2]
I just tried to get a non existing object from S3 with stream option set to true. The error callback was activated but never finished. 

To reproduce the problem, you can use the streaming example provided here.

**Comment by chilts** [comment]
Hi Giannis,

Can you provide me with the example script you're talking about?

Many thanks,
Andy

**Comment by kosmasgiannis** [comment]
Hi Andy,

The script I meant is the last one listed in the README.md, with a non-existent file of course.

Anyway here is what I used:

```
var fmt = require('fmt');
var amazonS3 = require('awssum-amazon-s3');

var s3 = new amazonS3.S3({
    'accessKeyId'     : process.env.ACCESS_KEY_ID,
    'secretAccessKey' : process.env.SECRET_ACCESS_KEY,
    'region'          : amazonS3.US_EAST_1
});

var options = {
    BucketName    : 'mybucketspace',
    ObjectName    : 'a-non-existent-file.txt',
};

s3.GetObject(options, { stream : true }, function(err, data) {
    if (err) {
        fmt.dump(err, 'err');
    } else {
        fmt.dump(data, 'data');

        // stream this file to stdout
        fmt.sep();
        fmt.title('The File');
        data.Stream.pipe(process.stdout);
        data.Stream.on('end', function() {
            fmt.sep();
        });
    }
});
```

The bug is not reproducible every time though, and only if the error object is printed. 
I suspect that the error object causes a cyclic reference that the GC does not detect properly.

I hope it helps.

Giannis

**Comment by chilts** [comment]
(deprecated: use aws-sdk)
