### ISSUE TITLE
How to forcefully close readable stream from GetObject ?

### ISSUE THREAD

**Issue by al6x** [chilts/awssum-amazon-s3#5]
Hello, is it possible to forcefully close readable stream from `GetObject` method
without getting all the data from it?

If the stream not drained it won't get closed automatically by itself, is it possible to somehow close it forcefully?

``` JavaScript
s3.GetObject(options, { stream : true }, function(err, data) {
  if(somethingBadHappanedInMyApplicationAndIDontWantToReadDataAnymore){
    data.Stream.closeForcefully()
  }
});
```

**Comment by chilts** [comment]
I think you can do something like `data.Stream.destroy()`. Let me know how it goes.
