### ISSUE TITLE
Document that using a bucket with a capital letter in the name will result in a SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by timhaines** [chilts/awssum-amazon-s3#6]
AWS allows capital letters in bucket names in the US east region.  Some apps work successfully with them, but awssum-amazon-s3 doesn't.

A capital letter in the name results in a SignatureDoesNotMatch error.

**Comment by chilts** [comment]
I have decided not to support this. Please see this comment for details : https://github.com/awssum/awssum/issues/164#issuecomment-27834732
