### ISSUE TITLE
PutObject using stream (not working)

### ISSUE THREAD

**Issue by khwaja** [chilts/awssum-amazon-s3#8]
PutObject-02-StreamingUpload.js example is not working. Looks like we are overriding the options.body in line 630 with undefined, if body is provided in args.

**Comment by chilts** [comment]
Hiya,

Which version of awssum-amazon-s3 are you using? If it's less than v1.3.1 please upgrade to this version and try again.

Many thanks,
Andy

**Comment by khwaja** [comment]
Yes. Its fixed now. Thanks
